name: flutter_expandable_column
description: "An expandable Flutter column widget that supports scrolling while allowing Expanded and Spacer widgets. Perfect for responsive layouts that need to fill available space."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
repository: https://github.com/rahul-gola/flutter_expandable_column
version: 0.0.3

topics:
  - flutter
  - widget
  - layout
  - scrollable
  - column

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
